### ISSUE TITLE
Create E2E tests with Protractor

### ISSUE THREAD

**Issue by arroyo** [Erdiko/user-admin#25]
start with one set of features and create tickets for the remaining features so we can eventually have the whole UI tested

- [x] Initial home page (login form) elements
- [x] Login form negative case
- [x] Login Form positive case
- [x] Logged In Home
- [x] User List
- [x] Used Edit
- [x] User Create

Formerly ER-132: Create E2E tests with Protractor on Trello

**Comment by saarmstrong** [comment]
Completed
