### ISSUE TITLE
Update Active / Inactive tab colors

### ISSUE THREAD

**Issue by saarmstrong** [Erdiko/user-admin#29]
We need to swap the active / inactive colors on the User Admin theme for tabs. See the attached screenshot![Cursor_and_Erdiko_User_Admin](http://static.gitscout.com/6fdc1b6a05bcd65ed6b6ccac9896b50ce4a6528d2a9132ff2b23035d25e99066.png)

**Comment by kkennethlee** [comment]
Yes, that crossed my mind. I honestly should have taken the initiative.
I'm on it.

**Comment by saarmstrong** [comment]
closed with merging of #35
