### ISSUE TITLE
Update Delete User modal buttons

### ISSUE THREAD

**Issue by saarmstrong** [Erdiko/user-admin#30]
Update the delete user modal buttons based on attached screenshot

![Cursor_and_Erdiko_User_Admin](http://static.gitscout.com/ac22674307cb59533fa97a5687aec7c982df44a808816968fc6b53befe43af04.png)

**Comment by kkennethlee** [comment]
![screen shot 2017-03-23 at 7 18 04 pm](https://cloud.githubusercontent.com/assets/15114745/24277901/7db500cc-0ffd-11e7-91ed-6c5b79832517.png)

**Comment by saarmstrong** [comment]
closed with merging of #36
