### ISSUE TITLE
Add Password entry on User Create form

### ISSUE THREAD

**Issue by saarmstrong** [Erdiko/user-admin#31]
Update the user create form to include 2 form fields to allow the user to set the password for a new user:

- Password
- Confirm Password

This should have the same validation as the exiting 'update password' tab. 

See the attached screenshot for rough placement.

![password](http://static.gitscout.com/60069c060112f08770f51467e6e5afeeb4e82e5ad27a9bddced44a1588c80382.png)

**Comment by kkennethlee** [comment]
Current Status: created a separate form-group. Will explore option for reducing the redundancy.

**Comment by saarmstrong** [comment]
This has been approved and merged.
