### ISSUE TITLE
Create a DropzoneJS Angular2 Component

### ISSUE THREAD

**Issue by saarmstrong** [Erdiko/user-admin#33]
Wrap the 3rd party JS library, DropzoneJS, into an Angular 2 component that we can use easily in our custom forms.

This component should also have a corresponding file input element that can be validated. This will be used in forms for file uploads.

-----

An existing plugin may (most likely) exists already that does this, but we need to make sure it covers all the functionality we need. We might go with an existing plugin, or roll our own depending on ease of use or issues with existing components.

Please come up with a list of existing plugins, list out their functionality, and come up with a short example for each.

**Comment by kkennethlee** [comment]
# Angular 2 _file drop_
- https://www.npmjs.com/package/ng2-file-drop
- **Dependency: tslerp**
  - https://www.npmjs.com/package/tslerp
  - `npm install typings --global`

- `npm install ng2-filedrop`
-  Directives:
    - `[ng2FileDropSupportedFileTypes]`
      - Takes in array of MIME types
      - `['image/png', 'image/jpeg', 'image/gif']`
    - `[ng2FileDropMaximumSizeBytes]`
      - Maximum file size in bytes
      - `fileSizeLimit: number = 1e+6`
    - `(ng2FileDropHoverStart)`
      - Assign it to a function for when item is inside the dropzone
    - `(ng2FileDropHoverEnd)`
      - Assign it to a function for when item is dragged outside the dropzone
    - `(ng2FileDropFileAccepted)`
      - Assign it to the function for when file is dropped and accepted
    - `(ng2FileDropFileRejected)`
      - Assign it to the function for when file is dropped and rejected

**Comment by kkennethlee** [comment]
# Angular 2 _ngx-dropzone-wrapper_
- https://www.npmjs.com/package/angular2-dropzone-wrapper
- `npm install ngx-dropzone-wrapper --save-dev`
-  Configuration options: http://www.dropzonejs.com/#configuration-options
    - Inside the `app.module.ts`
      -  `import { DropzoneModule } from 'ngx-dropzone-wrapper';`
      -  `import { DropzoneConfigInterface } from 'ngx-dropzone-wrapper';`
      -  `const DROPZONE_CONFIG: DropzoneConfigInterface ={  server: 'https://httpbin.org/post'  }` 
         -  **key** and **value** listed at http://www.dropzonejs.com/#configuration-options
     
-  Attributes: http://www.dropzonejs.com/#event-list
    - `[dropzone] = "config"`
      - Must have to define the `<div>` element to identify as dropzone
    - `(success)`
      - Assign to function when file meets the validity defined in the configuration
    - `(error)`
      - Assign it to a function when file fails to meet the validity defined in configuration
    -  Other events can be found in http://www.dropzonejs.com/#event-list
    -  Example:
       - `<div [dropzone]="config" (success)="onUploadSuccess($e)" (error)="onUploadError($e)"  </div>`

**Comment by arroyo** [comment]
both look promising, come up with an example of each.

**Comment by kkennethlee** [comment]
http://plnkr.co/edit/hqJFKLibUydMqIhjRNm1?p=preview

The way styling works is pretty confusing. Figuring out how it works will take some time.

**Comment by saarmstrong** [comment]
this component looks great! i like the functionality and seems to have all the expected config values we would need to tweak.

**Comment by saarmstrong** [comment]
@kkennethlee apologies, i moved this ticket before you were done. can you please provide an example for ng2-file-drop?

**Comment by arroyo** [comment]
do we have that second example yet?

**Comment by kkennethlee** [comment]
@arroyo @saarmstrong Working on it. I have an example set-up off line but there is a lot of dependencies so configuring it into Plunker will take some time.

**Comment by kkennethlee** [comment]
http://plnkr.co/edit/otXHqDKCHL1fGXGHTF1S?p=preview

**Comment by saarmstrong** [comment]
@kkennethlee thanks for the file-drop demo. while this library looks like it could be cool for usage, it looks like theres still some hoops to jump through for uploading a file.

also, a sticking point for mobile usage, this appears to only support drag-and-drop. i checked the docs and there does not seem to be a method to upload via tap events or with a mobile interface.

**Comment by arroyo** [comment]
we'll go with  ngx-dropzone-wrapper
