### ISSUE TITLE
Create install script to import example users

### ISSUE THREAD

**Issue by saarmstrong** [Erdiko/user-admin#41]
Create an install script that calls the two scripts in the erdiko/users package.  

Scripts are part of https://github.com/Erdiko/users/issues/32

**Comment by arroyo** [comment]
As I was writing the new tickets, I had an idea that may help here (and make the db scripts easier to maintain).  

Do Erdiko/users#32 first and then do this ticket as a wrapper (convenience script) to the 2 scripts create in 32.
