### ISSUE TITLE
Create technical architecture of how to store & retrieve user profile

### ISSUE THREAD

**Issue by arroyo** [Erdiko/user-admin#52]
Create architecture for how to configure user profile (backend and front-end).  Outline data structure to store (persist), theme and administer the profile.

Document accordingly.

Base on the latest wires from #51

**Comment by saarmstrong** [comment]
[UA-52_Tech_Architecture.pdf](https://github.com/Erdiko/user-admin/files/962278/UA-52_Tech_Architecture.pdf)

**Comment by saarmstrong** [comment]
Discussed documentation in internal meeting. Here is what we need to add/flush out:

* Profile elements definition should come from a static Config JSON file. This will allow us to add some simplification to the code and provide easier versioning. Also we can later abstract this out for alternative methods of data storage.
* Need to add elements about Security and Permissions
  * Add items detailing how user permissions will be enforced. (eg owner can edit, non-owner/non-admin can only read)
  * Add references to Erdiko User Authorize class into documentation
* Need to flush out more Profile Element JSON definitions.
  * Will need way to allow backend to validate data
  * Need concrete example of a Single User (Company or Video) element as well as generic elements (text field form).

**Comment by saarmstrong** [comment]
[ER-52.pdf](https://github.com/Erdiko/user-admin/files/977161/ER-52.pdf)

Latest Documentation for User Profile

**Comment by saarmstrong** [comment]
Reviewed and discussed document
